name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.EC2_USER }}/your-repo-name"
          rm: true # Optional: cleans target dir before copy

      - name: SSH and restart Flask app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd your-repo-name
            pip3 install --break-system-packages -r requirements.txt
            sudo systemctl daemon-reexec
            sudo systemctl daemon-reload
            sudo systemctl restart flaskapp
            sudo systemctl status flaskapp --no-pager
